all:
	python plot_traj.py
	python coupon_traj_vs_ODE.py
	python k_in_a_row.py

clean:
	rm -f dict_dist_N_K_coupon dict_dist_N_K_in_a_row
	rm -f gumbel_k1.pdf gumbel_k5.pdf
	rm -f simu_20.pdf simu_200.pdf simu_200_zoom.pdf
	rm -f erasure_channel.pdf 
